version: "3"
services:
  registry-sr:
    image: service-registry
    build: ./service-registry
    ports:
      - "8761:8761"
    networks:
      - app-network
  
#  zipkin-sr:
#    image: openzipkin/zipkin
#    ports:
#      - "9411:9411"
#    networks:
#      - app-network
  
#  config-sr:
#    image: config-server
#    build: ./config-server (3).zip_expanded/config-server
#    ports:
#      - "8088:8088"
#    networks:
#      - app-network
#    depends_on:
#      - registry-sr
#      - zipkin-sr
  
  api-gateway-sr:
    image: api-gateway
    build: ./api-gateway
    ports:
      - "8222:8222"
    networks:
      - app-network
    depends_on:
      - registry-sr
#      - zipkin-sr
#      - config-sr

  authentication-sr:
    image: authentication-service
    build: ./authentication-service
    ports:
      - "8090:8090"
    networks:
      - app-network
    depends_on:
      - registry-sr
#      - zipkin-sr
#      - config-sr
      - api-gateway-sr

  project-sr:
    image: project-info
    build: ./project-info
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - registry-sr
#      - zipkin-sr
#      - config-sr
      - api-gateway-sr
      - authentication-sr
  
  employee-sr:
    image: employee-info
    build: ./employee-info
    ports:
      - "8082:8082"
    networks:
      - app-network
    depends_on:
      - registry-sr
#      - zipkin-sr
#      - config-sr
      - api-gateway-sr
      - authentication-sr

#  mysqldb:
#     image: mysql:8
#     networks:
#       - app-network
#     environment:
#       - MYSQL_ROOT_PASSWORD=pass@word1
#       - MYSQL_DATABASE=mydb
#       - MYSQL_DATABASE=mydb2
#       - MYSQL_DATABASE=mydb3

networks:
  app-network: